# Change baseurl before deploy
baseurl = "https://github.com/OrangeEgg1937/"
languageCode = "zh-tw"
title = "Akua的IT狗Blog"
theme = "hugo-theme-stack"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-tw"

hasCJKLanguage = true
enableRobotsTXT = true

[services]
    [services.googleAnalytics]
        id = "G-W1EQ120P1Y"

[pagination]
pagerSize = 5

[sitemap]
    changefreq = "weekly"
    priority = 0.5
    filename = "sitemap.xml"